### ISSUE TITLE
Results not being rendered in table

### ISSUE THREAD

**Issue by aviral-batra** [avirut/obsidian-query2table#1]
I'm not sure if I'm doing it right, but no rows are being displayed in the table, and nothing is printing to the console.

![image](https://user-images.githubusercontent.com/68279653/104167660-a3ca4580-53f4-11eb-885f-7a967c7fb476.png)
![image](https://user-images.githubusercontent.com/68279653/104167688-adec4400-53f4-11eb-8652-3033e1f2a82e.png)

**Comment by avirut** [comment]
Thanks for the help debugging this, I've added information about how the YAML attribute for `note` must be present in order for the row to render.
