### ISSUE TITLE
Initial Set up Issues

### ISSUE THREAD

**Issue by santiyounger** [avirut/obsidian-query2table#5]
Hey, 

This plugin looks amazing, I'm excited to get it working

I get this error when I try to use it.

To be honest I'm a bit confused on exactly how every note should be formated in Frontmatter, 

I copied the example into a note added the saerch for a tag I created for test a tag called `#query-test`
like this:
```
```query2table
query: "tag:#query-test"
fields:
	- title: note
	- status: text
	- doi: link
	- topic: list
	- via: text
	- created: text
approxNumberOfResults: 5
```
I created a note called `test 1 query`

```
#query-test

testing query2table plugin

```

I'm not sure how to format the frontmatter in my `test 1 query` file, can you provide examples please?

The table is created correctly, and the search bar return the correct note, but the content of the table is empty

![image](https://user-images.githubusercontent.com/51902730/105764361-d449cd80-5f24-11eb-9106-245dadbd385f.png)

This is the error I get in the console, I copied the whole thing just in case, the end of it seems to be the error relevant to this plugin

```
app.js:1 Obsidian Developer Console
(unknown) loading plugin
(unknown) loading markdown-table-editor plugin
(unknown) Error: ENOENT: no such file or directory, open '/Users/santi/Dropbox/notes/obsidian/obsidian-personal/external-apps/citations/My-Library.json'
eval
(unknown) loading plugin: Cycle through panes
(unknown) Found existing settings file
(unknown) Loading Hotkeys++ plugin
(unknown) loading jump to links plugin
(unknown) Loading Mind Map plugin
(unknown) Loading natural language date parser plugin
(unknown) Loading Note Refactor plugin
(unknown) loading Vimrc plugin
(unknown) loading Obsidian_to_Anki...
(unknown) Loading the Review plugin.
(unknown) Object
(unknown) loading smart-random-note
(unknown) loading plugin
(unknown) loading plugin: query2table
(unknown) Vim is now set to yank to system clipboard.
(unknown) Clipboard change captured
index.html:222 Uncaught (in promise) TypeError: Cannot read property 'length' of null
    at Object.formatter (eval at <anonymous> (app.js:1), <anonymous>:222:77)
    at r.content (eval at <anonymous> (app.js:1), <anonymous>:105:41234)
    at r.render (eval at <anonymous> (app.js:1), <anonymous>:105:42163)
    at R (eval at <anonymous> (app.js:1), <anonymous>:105:7684)
    at N (eval at <anonymous> (app.js:1), <anonymous>:105:4267)
    at R (eval at <anonymous> (app.js:1), <anonymous>:105:7916)
    at N (eval at <anonymous> (app.js:1), <anonymous>:105:4267)
    at U (eval at <anonymous> (app.js:1), <anonymous>:105:9413)
    at R (eval at <anonymous> (app.js:1), <anonymous>:105:8099)
    at N (eval at <anonymous> (app.js:1), <anonymous>:105:4267)
```

Thanks for your work, looking forward to get this awesome plugin going!

**Comment by avirut** [comment]
Hi,

So, the search and the frontmatter are performed generally separately. Something like:
```
query: "tag:#query-test"
fields:
	- title: note
	- status: text
	- doi: link
	- topic: list
	- via: text
	- created: text
approxNumberOfResults: 5
```
will use the built in Obsidian search mechanism to get all notes with "tag:#query-test". In your case, the one file you created will be returned. However, the issue is that that file lacks frontmatter entirely, and most importantly doesn't have a `title` field in it's frontmatter.

In your other file, you can add frontmatter at the very top that looks like this...
```
---
title: This is a sample title
---
```
...and the note should show up in the table. All of the columns except for title will be blank (because they are unspecified), but it should show up nevertheless. The key is that the field marked "note" in the query2table codeblock *must* be present in the frontmatter, because that is the one that will link back to the note file.

Let me know if you have any more questions/are still having trouble!

**Comment by santiyounger** [comment]
Hey, thanks a lot for clearing that up! 

Now that I've added the following to my note:
```
---
title: This is a test
---
```

It looks like this:

![image](https://user-images.githubusercontent.com/51902730/105850141-554da700-5faf-11eb-98fb-2f28e8a57757.png)

---

When I go back to my query note I have things written this way

![image](https://user-images.githubusercontent.com/51902730/105850119-4b2ba880-5faf-11eb-849c-0bd7e9f77c71.png)

---

When I go into preview mode, it get's stuck on this `loading...` state

![image](https://user-images.githubusercontent.com/51902730/105850086-42d36d80-5faf-11eb-8f9a-976a7d9713b5.png)

---

If I reload obsidian I just get this

![image](https://user-images.githubusercontent.com/51902730/105850535-dad15700-5faf-11eb-9c91-f6e2983c3d7a.png)


---

Not sure what the issue might be, seems to be like things are correctly formatted now, let me know if there's something I might be missing though.

Also let me know if there's any more info or tests I should run.

I'm not sure if it might be a linux issue though, could it be?


Thank you!

**Comment by avirut** [comment]
I doubt that it's a Linux issue since I am not using any filesystem related APIs, just things built into Obsidian. Can you check what happens if:
1) You get rid of everything in the codeblock under `fields` except for `title: note`
2) You change the tag to something without a dash in it (this shouldn't make a difference, but just in case)

Please check in the developer console once again and let me know what, if anything, pops up. Appreciate your help debugging!

**Comment by santiyounger** [comment]
Got you, so I did is as you instructed, this time in an empty vault without any othe plugins

![image](https://user-images.githubusercontent.com/51902730/106070068-c1c0c700-60d1-11eb-9218-1935e7899c4c.png)

![image](https://user-images.githubusercontent.com/51902730/106070038-b4a3d800-60d1-11eb-9776-ad4d7c55a683.png)

## it seems to have worked
with the instructions you provided
![image](https://user-images.githubusercontent.com/51902730/106070457-7d81f680-60d2-11eb-9092-93e5c4c5769e.png)


If I do exactly what I did in the previous test in an empty vault it doesn't work. It only works if I follow the steps you mentioned.

---

Weirdly though, if I do this in my main vault where I have many other plugins it doesn't work.

I know there's another plugin that has been giving me issues, so it might be a conflict with that.

This is my main vault's console log just in case (at the end of this comment)

---

Thank you so much for your help, excited to get this plugin going.

I'll definetly try to see what is it in my mail vault that's causing conflicts, but it's still strange that things only worked after I followed the steps you mentioned


Let me know if you'd like me to run more tests, I'm happy to help until things work alright!

```
app.js:1 Obsidian Developer Console
(unknown) loading plugin
(unknown) loading markdown-table-editor plugin
(unknown) loading plugin: Cycle through panes
(unknown) Found existing settings file
(unknown) Loading Hotkeys++ plugin
(unknown) loading jump to links plugin
(unknown) Loading Mind Map plugin
(unknown) Loading natural language date parser plugin
(unknown) Loading Note Refactor plugin
(unknown) loading Vimrc plugin
(unknown) loading Obsidian_to_Anki...
(unknown) Loading the Review plugin.
(unknown) Object
(unknown) loading smart-random-note
(unknown) loading plugin
(unknown) loading plugin: query2table
(unknown) Vim is now set to yank to system clipboard.
(unknown) Clipboard change captured
(unknown) Yank captured
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
main.ts:99 Yank captured
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
main.ts:99 Yank captured
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8765/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
(unknown) Clipboard change captured
```

**Comment by avirut** [comment]
So, I tested out the having a dash in the tag part and it doesn't seem to matter. I was able to reproduce the part where it gets stuck on "Loading..." and then shows no entries, however, so there definitely is some issue with the plugin. There may also be some problems/conflicts with your other plugins - unfortunately, it's just too hard to figure out right now.

If you do happen to figure anything out, let me know. Unfortunately, I won't really have any significant time to spend improving my plugins for the next few months, so short of quick fixes, this project has to go on hold for me for a while.

**Comment by santiyounger** [comment]
No worries, if I find out any conflicts with other plugins I'll make sure to let you know. and don't worry I get you, these things take time and I do realize it's a passion project, so I'm happy to wait and see this plugin evolve with time!

Thanks for making it, and I'll keep an eye for it!

Thanks a lot for the help

**Comment by johnghill** [comment]
Also experiencing this issue (perpetual "Loading...") on the following environment
```
plugin: 0.1.1
obsidian: v0.11.5
os: 5.4.101-1-MANJARO x86_64
```

Scaling back to a simplified test of one field (`- title: note`) did not resolve the issue. Interestingly, the query results are correctly displayed in Obsidian's query pane.

**Comment by avirut** [comment]
You've probably already discovered it, but I'd recommend giving [Obsidian Dataview](https://github.com/blacksmithgu/obsidian-dataview) a shot. It does most of what query2table did, and far better.
